// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can create these using the Firebase Console.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can create these using the Firebase Console.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can create these using the Firebase Console.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can create these using the Firebase Console.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2lt0mRJR2QAU8vKOVKydaorUa_NcQHoI',
    appId: '1:611828740822:android:0f77752ff0e203d43ecf77',
    messagingSenderId: '611828740822',
    projectId: 'zediatask',
    storageBucket: 'zediatask.firebasestorage.app',
  );

  // You should replace these placeholders with actual values from your Firebase project

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiqEfpm264oPk2g9PWXVVwlvZyUrOxkIg',
    appId: '1:611828740822:ios:01552e8b773601143ecf77',
    messagingSenderId: '611828740822',
    projectId: 'zediatask',
    storageBucket: 'zediatask.firebasestorage.app',
    iosBundleId: 'com.zediasolutions.zediatask',
  );

} 